accu_project/SourceCode/accu_dashboard/urls.py
from django.urls import path
from django.conf.urls import url, include

from accu_dashboard import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),  
    path('index-ms', views.IndexDashBoard.as_view(), name='index_ms'),  
    path('index-md', views.IndexMD.as_view(), name='index_md'),  
    path('index-mpd', views.IndexMPD.as_view(), name='index_mpd'),  
    path('index-accu', views.IndexACCU.as_view(), name='index_accu'),  
    url(r'^get-data-summary$', views.get_data_summary),
    url(r'^get-data-md$', views.get_data_md),
    url(r'^get-data-mpd$', views.get_data_mpd),
    url(r'^get-data-accu$', views.get_data_accu),
    url(r'^test$', views.test),
    url(r'^import-data$', views.import_data),
    url(r'^import-data-accu$', views.import_data_accu),
    url(r'^import-data-accu-1$', views.import_data_accu_1), #
    url(r'^import-data-accu-2$', views.import_data_accu_2), #

    path('index-log', views.IndexLog.as_view(), name='index_log'),  
    path('index-site', views.IndexDataSOH.as_view(), name='index-site'),
    path('index-site-data', views.IndexDataSOHConvert.as_view(), name='index-site-data'),
    

    url(r'^preview-import-data$', views.preview_data_import),
    url(r'^save-import-data$', views.save_data_import),
    url(r'^del-log$', views.del_log),

    
    # Export data excel
    url(r'^export-data-summary$', views.export_data_summary),
    url(r'^export-data-summary-md$', views.export_data_summary_md),
    url(r'^export-data-summary-mpd$', views.export_data_summary_mpd),
    url(r'^export-data-summary-accu$', views.export_data_summary_accu),

    # Data new
    path('import-data-source-info', views.import_data_source_info),
    path('import-data-accu-info', views.import_data_accu_info),
    path('import-data-mpd-info', views.import_data_mpd_info),
    path('import-data-ats-info', views.import_data_ats_info),

    
    path('mpd-index', views.MPDIndex.as_view(), name='mpd_index'),  
    url(r'^get-data-mpd-info$', views.get_data_mpd_info),
    path('ajax/load-update-mpd-info', views.load_update_mpd_info),
    path('ajax/update-mpd-info', views.update_mpd_info),
    path('mpd/<int:pk>/delete', views.MPDInfoDeleteView.as_view(), name='mpd_info_delete'),    

    # ATS INFO
    path('ats-index', views.ATSIndex.as_view(), name='ats_index'),  
    url(r'^get-data-ats-info$', views.get_data_ats_info),
    path('ajax/load-update-ats-info', views.load_update_ats_info),
    path('ajax/update-ats-info', views.update_ats_info),
    path('ats/<int:pk>/delete', views.ATSInfoDeleteView.as_view(), name='ats_info_delete'), 

    # CabinetsSource 
    path('cabinet-index', views.CabinetIndex.as_view(), name='cabinet_index'),  
    url(r'^get-data-cabinet$', views.get_data_cabinets),
    path('ajax/load-update-cabinet', views.load_update_cabinets),
    path('ajax/update-cabinet', views.update_cabinets),
    path('cabinet/<int:pk>/delete', views.CabinetDeleteView.as_view(), name='cabinet_delete'), 
    
    # ACCU INFO
    path('accu-index', views.ACCUIndex.as_view(), name='accu_index'),  
    url(r'^get-data-accu-info$', views.get_data_accu_info),
    path('ajax/load-update-accu-info', views.load_update_accu_info),
    path('ajax/update-accu-info', views.update_accu_info),
    path('accu/<int:pk>/delete', views.ACCUInfoDeleteView.as_view(), name='accu_info_delete'),

    path('test-cron', views.run_sync_data_r_alarm_log_ms_query),  
    
    path('soh-index', views.DataSOHIndex.as_view(), name='soh_index'),  
    url(r'^get-data-soh-info$', views.get_data_soh_info),
    path('soh/<int:pk>/delete', views.DataSOHInfoDeleteView.as_view(), name='soh_info_delete'),
]  

accu_project/SourceCode/main/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from main import views

urlpatterns = [
    path('admin/login/', views.redirect_login),
    path('admin/', admin.site.urls),
    path('customers/', include('f_1_1_customers.urls')), 
    path('sites/', include('f_1_2_sites.urls')), 
    path('accounts/', include('f_7_1_accounts.urls')), 
    path('accounts/', include('django.contrib.auth.urls')), 
    path('', include('accu_dashboard.urls')),


]

accu_project/SourceCode/accu_dashboard/models.py
from django.db import models
from datetime import datetime
from f_1_2_sites.models import Site




# Create your models here.
NETWORK_TYPE_CHOICES = (
  ("2g","2G"),
  ("3g","3G"),
  ("4g","4G"),
  ("5g","5G"),
)

def _get_offset_query_data_table( index=1, pagination=50):
    """Hàm get ra ofset start + offset end khi query data

    Args:
      index (int): index của pagination (1,2,3,4....)
      pagination (int): Limit phân trang (50, 100)
    
    Return : 
    Tuple :  start_index:int, total_record:int
    
    
    """
    start_offset = pagination*(index-1)
    total_record = pagination
    
    return start_offset,total_record

class R_ALARM_LOG(models.Model):
  district = models.CharField(null=True, max_length=255)
  provice = models.CharField(null=True, max_length=255, )
  groups = models.CharField(null=True, max_length=255)
  durations = models.IntegerField(null=True, default=0)
  network = models.CharField(null=True, max_length=255)
  vendor = models.CharField(null=True, max_length=255)
  ne = models.CharField(null=True, max_length=255)
  site = models.CharField(null=True, max_length=255)
  sdate = models.DateTimeField(null=True, verbose_name="")
  edate = models.DateTimeField(null=True, verbose_name="")
  alarm_type = models.CharField(null=True, max_length=255)
  alarm_name = models.CharField(null=True, max_length=255)
  alarm_info = models.CharField(null=True, max_length=2555)

  def get_data_alarm(self, start_date, end_date, page=1, page_size=50):

    sql_query = f"""
      SELECT id,NETWORK,SITE,SDATE,EDATE,DURATIONs,PROVICE,DISTRICT,GROUPS
        FROM accu_dashboard_r_alarm_log 
        where alarm_info like  '%Main AC Alarm%'
        and sdate >= date('{start_date}')
        and sdate <= date('{end_date}')  
      
    """ 
    start_offset,total_record = _get_offset_query_data_table(int(page), int(page_size))

    sql_query += f" LIMIT {start_offset }, {total_record}"

    return R_ALARM_LOG.objects.raw(sql_query)

  def get_data_alarm_export(self, start_date, end_date):

    sql_query = f"""
      SELECT id,NETWORK,SITE,SDATE,EDATE,DURATIONs,PROVICE,DISTRICT,GROUPS
        FROM accu_dashboard_r_alarm_log 
        where alarm_info like  '%Main AC Alarm%'
        and sdate >= date('{start_date}')
        and sdate <= date('{end_date}')  
      
    """ 

    return R_ALARM_LOG.objects.raw(sql_query)  

  def get_total_data_alarm(self, start_date, end_date):

    sql_query = f"""
      SELECT id
        FROM accu_dashboard_r_alarm_log 
        where alarm_info like  '%Main AC Alarm%'
        and sdate >= date('{start_date}')
        and sdate <= date('{end_date}')  
      
    """ 

    return len(R_ALARM_LOG.objects.raw(sql_query))

  def get_data_MD(self, start_date, end_date,page=1,page_size=50):
    sql_query = f"""
      SELECT *
        FROM accu_dashboard_r_alarm_log 
        WHERE alarm_type = 'POWER'
        and sdate >= date('{start_date}')
        and sdate <= date('{end_date}')  ORDER BY durations DESC
      
    """ 
    start_offset,total_record = _get_offset_query_data_table(int(page), int(page_size))

    sql_query += f" LIMIT {start_offset }, {total_record}"

    return R_ALARM_LOG.objects.raw(sql_query)

  def get_data_MD_export(self, start_date, end_date):
    sql_query = f"""
      SELECT *
        FROM accu_dashboard_r_alarm_log 
        WHERE alarm_type = 'POWER'
        and sdate >= date('{start_date}')
        and sdate <= date('{end_date}')  ORDER BY durations DESC
      
    """ 

    return R_ALARM_LOG.objects.raw(sql_query)  

  def get_total_data_MD(self, start_date, end_date):
    sql_query = f"""
      SELECT id
        FROM accu_dashboard_r_alarm_log 
        WHERE alarm_type = 'POWER'
        and sdate >= date('{start_date}')
        and sdate <= date('{end_date}')  ORDER BY durations DESC
      
    """ 

    return len(R_ALARM_LOG.objects.raw(sql_query))
  
  def get_data_MPD(self, start_date, end_date, page=1, page_size = 50):
    sql_query = f"""
      SELECT id , provice, groups, network, alarm_type , SUM(durations) as total_durations
        FROM accu_dashboard_r_alarm_log 
        WHERE alarm_type = 'GENERATOR'
        and sdate >= date('{start_date}')
        and sdate <= date('{end_date}') GROUP BY  provice,network ORDER BY durations DESC
      
    """ 
    # start_offset,total_record = _get_offset_query_data_table(int(page), int(page_size))

    # sql_query += f" LIMIT {start_offset }, {total_record}"

    return R_ALARM_LOG.objects.raw(sql_query)

  def get_data_MPD_export(self, start_date, end_date,):
    sql_query = f"""
      SELECT *
        FROM accu_dashboard_r_alarm_log 
        WHERE alarm_type = 'GENERATOR'
        and sdate >= date('{start_date}')
        and sdate <= date('{end_date}')  ORDER BY durations DESC
      
    """ 

    return R_ALARM_LOG.objects.raw(sql_query)  

  def get_total_data_MPD(self, start_date, end_date):
    sql_query = f"""
      SELECT id
        FROM accu_dashboard_r_alarm_log 
        WHERE alarm_type = 'GENERATOR'
        and sdate >= date('{start_date}')
        and sdate <= date('{end_date}')  ORDER BY durations DESC
      
    """ 


    return len(R_ALARM_LOG.objects.raw(sql_query))

#  and durations >= {duration_less} and durations <= {duration_more}    
class R_ALARM_LOG_Check(models.Model):
  date = models.DateTimeField(null=True, verbose_name="")
  is_syns = models.BooleanField(default=False)

class ACCUMSData(models.Model):
  district = models.CharField(null=True, max_length=255)
  provice = models.CharField(null=True, max_length=255, )
  groups = models.CharField(null=True, max_length=255)
  network = models.CharField(null=True, max_length=255)
  site = models.CharField(null=True, max_length=255)
  md_sdate = models.DateTimeField(null=True, verbose_name="")
  sdate = models.DateTimeField(null=True, verbose_name="")
  edate = models.DateTimeField(null=True, verbose_name="")


class ACCUTable(models.Model):
  district = models.CharField(null=True, max_length=255)
  provice = models.CharField(null=True, max_length=255, )
  groups = models.CharField(null=True, max_length=255)
  network = models.CharField(null=True, max_length=255)
  site = models.CharField(null=True, max_length=255)
  sdate = models.DateTimeField(null=True, verbose_name="")
  edate = models.DateTimeField(null=True, verbose_name="")
  durations = models.IntegerField(null=True, default=0)

  def get_data_accu(self, start_date, end_date, type_network, duration_less=0, duration_more=30):

    # sql_query = f"""
    #   SELECT id,NETWORK,SITE,SDATE,EDATE,DURATIONs,PROVICE,DISTRICT,GROUPS
    #     FROM accu_data 
    #     where durations >= {duration_less} and durations <= {duration_more}
    #     and sdate >= date('{start_date}')
    #     and sdate <= date('{end_date}')  
    #     and network = '{type_network}'
      
    # """ 

    sql_query = f"""
      SELECT id,NETWORK,SITE,SDATE,EDATE,DURATIONs,PROVICE,DISTRICT,GROUPS
        FROM accu_data 
        where sdate >= date('{start_date}')
        and sdate <= date('{end_date}')  
        and network = '{type_network}'
      
    """ 

    return ACCUTable.objects.raw(sql_query)
  
  def get_data_ACCU(self, start_date, end_date, page=1,page_size=50):
    sql_query = f"""
      SELECT *
        FROM accu_data
        WHERE sdate >= date('{start_date}')
        and sdate <= date('{end_date}')  ORDER BY durations DESC
      
    """ 
    start_offset,total_record = _get_offset_query_data_table(int(page), int(page_size))

    sql_query += f" LIMIT {start_offset }, {total_record}"

    print(sql_query)
    return ACCUTable.objects.raw(sql_query)

  def get_data_ACCU_export(self, start_date, end_date):
    sql_query = f"""
      SELECT *
        FROM accu_data
        WHERE sdate >= date('{start_date}')
        and sdate <= date('{end_date}')  ORDER BY durations DESC
      
    """ 

    return ACCUTable.objects.raw(sql_query)  

  def get_total_data_ACCU(self, start_date, end_date):
    sql_query = f"""
      SELECT *
        FROM accu_data
        WHERE sdate >= date('{start_date}')
        and sdate <= date('{end_date}')  ORDER BY durations DESC
      
    """ 

    return len(ACCUTable.objects.raw(sql_query))
  
  class Meta:
    db_table = 'accu_data'
  

class SiteInfo(models.Model):
  site = models.CharField(null=True, max_length=255)
  district = models.CharField(null=True, max_length=255)
  type_network = models.CharField("network",max_length=20, choices=NETWORK_TYPE_CHOICES, default="")
  provice = models.CharField(null=True, max_length=255, )
  groups = models.CharField(null=True, max_length=255)

  class Meta:
    db_table = "site_info"


class ACCUDataLog(models.Model):
  file_name = models.CharField(null=True, max_length=255)
  created_date = models.DateTimeField(auto_now_add=True,null=True)

  class Meta:
    db_table = "accu_data_log" 


class ACCUData(models.Model):
  site = models.CharField(null=True, max_length=255)
  number_of_jar = models.IntegerField(null=True)
  brand = models.CharField(null=True, max_length=255)
  voltage = models.IntegerField(null=True)
  capacity = models.IntegerField(null=True)
  backup_time = models.IntegerField(null=True)
  dc_current_consumption = models.FloatField(null=True)
  day_enter_active = models.DateTimeField(null=True)
  log = models.ForeignKey(ACCUDataLog, on_delete=models.SET_NULL, null=True)

  class Meta:
    db_table = "accu_data_import"


class MPDInfo(models.Model):
  name = models.CharField(null=True, max_length=255 )
  code = models.CharField(null=True, max_length=255 )
  product_code = models.CharField(null=True, max_length=255 )
  qr_code = models.CharField(null=True, max_length=255 )
  wattage = models.FloatField(default=0) # Cong suat
  phase = models.CharField(null=True, max_length=255 )
  site = models.ForeignKey(Site, on_delete=models.SET_NULL, null=True)
  parent_code = models.CharField(null=True, max_length=255 )
  parent_name = models.CharField(null=True, max_length=255 )

accu_project/SourceCode/templates/apps/accu_dashboard/dashboard-accu.html
{% extends 'base/base.html' %}

{% block link %}
<style>

</style>
{% endblock %}

{% block main %}
<div class="container-fluid">
    <h1 class="pt-4 font-weight-bold text-mobi mb-3">
        Summary ACCU
    </h1>

    <div class="row">
        <div class="col-12">
            <div class="table-loading">
                <div class="row position-relative">
                    <div class="col-12">
                        
                        <div class="row">
                            <div class="col-10 d-flex">
                                <select class="form-control form-control-toolbar form-control-sm mr-3" id="time-duration"
                                    onchange="load_data()">
                                    <option value="-1">- Time duration -</option>
                                    <option value="1" {{ "selected" if request.GET.get('type')=='1' }}>0-5</option>
                                    <option value="2" {{ "selected" if request.GET.get('type')=='2' }}>5-15</option>
                                    <option value="3" {{ "selected" if request.GET.get('type')=='3' }}>15-30</option>
                                    <option value="4" {{ "selected" if request.GET.get('type')=='4' }}>30-60</option>
                                    <option value="5" {{ "selected" if request.GET.get('type')=='5' }}>more than 60</option>
                                </select>

                                <div id="reportrange" class="mr-3">
                                    <i class="fa fa-calendar"></i>&nbsp; <span></span>
                                    <i class="fa fa-caret-down"></i>
                                </div>

                                <button class="btn btn-light border btn-sm button-daterange-and-btn" onclick="load_data()" style="pointer-events: auto; opacity: 1; height: 28px;">Load data</button>
                            </div>
                            <div class="col-2">
                                <button class="btn btn-light border btn-sm float-right mb-2" onclick="download_summary_accu();">
                                    <i></i>Export Excel
                                </button>
                            </div>
                        
                        </div>
    
                    </div>
    
                    <div class="col-12 mt-2" id='data-content-accu'>
                    </div>
                </div>
    
            </div>
        </div>
    </div>
</div>


{% endblock main %}

{% block script %}
<script type="text/javascript">

    function load_data(){
        var date = get_start_date_and_end_date("reportrange");
        _start_date = date.start_date;
        _end_date = date.end_date;
         // Get Data From URL
         var params = new URLSearchParams(window.location.search);
        var _page = 1
        var _page_size = 50
        if(params.get("page")){
        _page = parseInt(params.get("page"))
        }

        if(params.get("page_size")){
        _page_size = parseInt(params.get("page_size"))
        }

        if(params.get("start_date")){
            _start_date = params.get("start_date");
        }

        if(params.get("end_date")){
            _end_date = params.get("end_date");
        }

        disable_element($(" .table-loading"));
        $.ajax({
        type: "POST",
        url: "/get-data-accu",
        dataType: "html",
        data : {
            "start_date" : _start_date,
            "end_date" : _end_date,
            'page': _page,
            'page_size': _page_size,
            'csrfmiddlewaretoken': '{{ csrf_token }}' 
        },
        success : function(response) {
            enable_element($(" .table-loading"));
            $('#data-content-accu').html(response);

        },
        error: function(xhr, status, e) {

        }
        });


    }

    $(document).ready(function () {

        initCalendar();
        var params = new URLSearchParams(window.location.search);
        var _start_date = '{{current_start_time}}';
        var _end_date = '{{current_end_time}}';
        if(params.get("start_date")){
            _start_date = params.get("start_date");
        }

        if(params.get("end_date")){
            _end_date = params.get("end_date");
        }
        $("#reportrange span").html( _start_date+ " - " + _end_date);

        //Load data
        load_data();


    });

    function initCalendar() {
        init_calendar("reportrange");
        var date = get_start_date_and_end_date("reportrange");
        _start_date = date.start_date;
        _end_date = date.end_date;
    }


</script>
{% endblock %}

accu_project/SourceCode/templates/apps/accu_dashboard/dashboard-md.html
{% extends 'base/base.html' %}

{% block main %}
<div class="container-fluid my-3">
    <div class="row">
        <div class="col-12">
            <h2 class="pt-2 font-weight-bold pl-3 mb-0 text-mobi">
                Summary MD
            </h2>
        </div>
        <div class="col-12">
            <div class="table-loading">
                <div class="row mx-3 position-relative mt-3">
                    <div class="col-10 pl-0">
                        <div class="d-flex">
                            <div class="d-inline mr-3">
                                <div id="reportrange">
                                    <i class="fa fa-calendar"></i>&nbsp; <span></span>
                                    <i class="fa fa-caret-down"></i>
                                </div>
                            </div>
                            <div class="d-inline">
                                <button 
                                    class=" border btn-sm button-daterange-and-btn" 
                                    onclick="load_data()" 
                                    style="pointer-events: auto; opacity: 1;">
                                    <i class="fa fa-play-circle mr-1"></i>Load data
                                </button>
                            </div>
                        </div>
                    </div>
    
                    <div class="col-2">
                        <button class="btn btn-light border btn-sm float-right mb-2" onclick="download_summary_md();">
                            <i class="fa fa-download mr-1"></i>Export Excel
                          </button>
                    </div>
    
                    <div class="col-12 pl-0" id='data-content-md'>
                    </div>
                </div>
    
            </div>
        </div>
    </div>
</div>
{% endblock main %}

{% block script %}
<script type="text/javascript">

    function load_data(){
        var date = get_start_date_and_end_date("reportrange");
        _start_date = date.start_date;
        _end_date = date.end_date;
         // Get Data From URL
         var params = new URLSearchParams(window.location.search);
        var _page = 1
        var _page_size = 50
        if(params.get("page")){
            _page = parseInt(params.get("page"));

        }

        if(params.get("start_date")){
            _start_date = params.get("start_date");
        }

        if(params.get("end_date")){
            _end_date = params.get("end_date");
        }

        if(params.get("page_size")){
        _page_size = parseInt(params.get("page_size"))
        }

        disable_element($(" .table-loading"));
        $.ajax({
        type: "POST",
        url: "/get-data-md",
        dataType: "html",
        data : {
            "start_date" : _start_date,
            "end_date" : _end_date,
            'page' : _page,
            'page_size' : _page_size,
            'csrfmiddlewaretoken': '{{ csrf_token }}' 
        },
        success : function(response) {
            enable_element($(" .table-loading"));
            $('#data-content-md').html(response);

        },
        error: function(xhr, status, e) {

        }
        });


    }

    $(document).ready(function () {

        initCalendar();
        var params = new URLSearchParams(window.location.search);
        var _start_date = '{{current_start_time}}';
        var _end_date = '{{current_end_time}}';
        if(params.get("start_date")){
            _start_date = params.get("start_date");
        }

        if(params.get("end_date")){
            _end_date = params.get("end_date");
        }
        $("#reportrange span").html( _start_date+ " - " + _end_date);

        //Load data
        load_data();


    });

    function initCalendar() {
        init_calendar("reportrange");
        var date = get_start_date_and_end_date("reportrange");
        _start_date = date.start_date;
        _end_date = date.end_date;
    }


</script>
{% endblock %}

accu_project/SourceCode/templates/apps/accu_dashboard/dashboard.html
{% extends 'base/base.html' %}

{% block link %}
<style>
    .canvas-minute {
        margin-bottom: 40px !important;
    }
</style>
{% endblock %}

{% block main %}
<div class="row mt-4 mx-4">
    <div class="col-12">
        <div id="main-content" class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <h2 class="py-2 font-weight-bold text-mobi">
                        DASHBOARD
                    </h2>
                </div>
            </div>

            <div class="row pl-3">
                <div id="reportrange" class="col-2">
                    <i class="fa fa-calendar"></i>&nbsp; <span></span>
                    <i class="fa fa-caret-down"></i>

                </div>
                <div class="col-4">
                    <div class="border-right d-inline-block" style="width: 93px">
                        <button class=" border btn-sm button-daterange-and-btn" onclick="change_date()" style="pointer-events: auto; opacity: 1;">Load data</button>
                    </div>

                    <select class="form-control form-control-toolbar form-control-sm ml-3" id="id_type" onchange="add_param()">
                        <option value="1" >- Đài -</option>
                        <option value="2" {{ "selected" if request.GET.get('type') == '2' }}>- Tỉnh -</option>
                        <option value="3" {{ "selected" if request.GET.get('type') == '3' }}>- Huyện -</option>
                    </select>


                    <div class="d-none" id='select_provice'>
                        <select class="form-control form-control-toolbar form-control-sm ml-3" id="id_provice" onchange="add_param()">
                            <option value="-1" >- ALL Tỉnh -</option>
                            {% for provice in list_provices  %}
                                <option value="{{loop.index -1}}" {{ "selected" if request.GET.get('provice') == (loop.index -1)|string }}>{{provice}}</option>
                            {% endfor %}
                        </select>
                    </div>

                    
                </div>

                <div class="col-2"></div>
                <div class="col-4"></div>
            </div>

            <div class="row" style="margin-top: 20px;" id="box-2g">
                <div class="col-8"></div>
                <div class='col-4' id="div-provice"></div>
            </div>

            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <h4 class="ml-4 mb-3">CHẤT LƯỢNG ACQUY THEO LOẠI (2,3,4)G</h4>
                    </div>
                    <div class="row">
                        <div class="p-0 col-4" id="power-off-2G" >
                            {% include 'apps/accu_dashboard/detail-dashboard/power-off-2G.html' %}
                        </div>
        
                        <div class=" col-4 p-0" id="power-off-3G" >
                            {% include 'apps/accu_dashboard/detail-dashboard/power-off-3G.html' %}
                        </div>
        
                        <div class=" col-4 p-0" id="power-off-4G" >
                            {% include 'apps/accu_dashboard/detail-dashboard/power-off-4G.html' %}
                        </div>
        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">

    function change_date() {
        disable_element($("#main-content"));
        var date = get_start_date_and_end_date("reportrange");
        _start_date = date.start_date;
        _end_date = date.end_date;
        window.location.search = `?start_date=${_start_date}&end_date=${_end_date}`



    };

    $(document).ready(function () {

        initCalendar();

        $("#reportrange span").html('{{current_start_time}}' + " - " + '{{current_end_time}}');

        var type = $("#id_type").val();

        // Check provice 
        if(type==3){
            $('#select_provice').addClass('d-inline-block');
            $('#select_provice').removeClass('d-none');
        }else{
            $('#select_provice').removeClass('d-inline-block');
            $('#select_provice').addClass('d-none');
        }


    });

    function initCalendar() {
        init_calendar("reportrange");
        var date = get_start_date_and_end_date("reportrange");
        _start_date = date.start_date;
        _end_date = date.end_date;
    }

    function add_param() {
        //disable_element($(".table-loading"));
        var type = $("#id_type").val();

        var id_provice = $('#id_provice').val()


        var date = get_start_date_and_end_date("reportrange");
        _start_date = date.start_date;
        _end_date = date.end_date;
        window.location.search = `?type=${type}&start_date=${_start_date}&end_date=${_end_date}&provice=${id_provice}`


        
    };



$('#id_provice').select2({
  theme: 'bootstrap',
  placeholder: 'Select Provice',
  allowClear: false
});



</script>

{% endblock main %}

accu_project/SourceCode/templates/apps/accu_dashboard/goolge-map.html
<html >
<body onLoad="initialize()">
                  <div class="col-sm-offset-1" id="map_canvas" style="width:500; height:500"></div>
                  <br>
                  <input type="text" id="lat">
                  <input type="text" id="lng">            
<script src="http://maps.google.com/maps/api/js?sensor=false" type="text/javascript"></script> 
<style>
  body{
    text-align:center;
  }
  .gmap3{
    margin: 20px auto;
    border: 1px dashed #C0C0C0;
    width: 500px;
    height: 500px;
  }
</style>    
<script type="text/javascript">
   var map;
 function initialize() {
 var myLatlng = new google.maps.LatLng(36.85341604753753,10.176080866332995);
 var myOptions = {
 zoom: 14,
 minZoom:14,
 center: myLatlng,
 draggable:false,
 mapTypeId: google.maps.MapTypeId.SATELLITE
 }
map = new google.maps.Map(document.getElementById("map_canvas"), myOptions); 
 var marker = new google.maps.Marker({


draggable: true,
position: myLatlng, 
map: map,
  });
google.maps.event.addListener(marker, 'dragend', function (event) {
document.getElementById("lat").value = this.getPosition().lat();
document.getElementById("lng").value = this.getPosition().lng();
}
); 
}
</script>
</body>
</html>