accu_project/SourceCode/f_1_1_customers/urls.py
# blog/urls.py
from django.urls import path
from f_1_1_customers import views
from django.conf.urls import url, include


urlpatterns = [
    


]
  

accu_project/SourceCode/main/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from main import views

urlpatterns = [
    path('admin/login/', views.redirect_login),
    path('admin/', admin.site.urls),
    path('customers/', include('f_1_1_customers.urls')), 
    path('sites/', include('f_1_2_sites.urls')), 
    path('accounts/', include('f_7_1_accounts.urls')), 
    path('accounts/', include('django.contrib.auth.urls')), 
    path('', include('accu_dashboard.urls')),


]

accu_project/SourceCode/f_1_1_customers/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import Group
from django.contrib.auth import get_user_model
from datetime import datetime
from dateutil.relativedelta import relativedelta

from f_1_2_sites.models import Site
# Create your models here.
class CustomerGroup(models.Model):
  name = models.CharField(max_length=50)
  site = models.ManyToManyField(Site, blank=True, verbose_name="契約サイト")

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('customer_group_list')
  
  class Meta:
    db_table = 'customer_group'

class Customer(models.Model):
  id = models.CharField(
    max_length=6,
    unique=True,
    primary_key=True
  )
  code = models.CharField(max_length=30, verbose_name="顧客コード")
  exclude_email = models.TextField(verbose_name="除外メールアドレス", help_text="例：@tpcompany.net")
  email_domain = models.TextField(verbose_name="除外ドメイン", help_text="例：tpcompany.net")
  name = models.CharField(max_length=30, verbose_name="顧客名")
  created_date = models.DateTimeField(auto_now_add=True, verbose_name="作成日")
  last_updated = models.DateTimeField(auto_now=True, verbose_name="更新日")
  domain = models.CharField(max_length=100,blank=True, verbose_name="サイトURL", help_text="例：https://www.tpcompany.net")
  customer_group = models.ForeignKey(CustomerGroup, on_delete=models.CASCADE, verbose_name="グループ")
  site = models.ManyToManyField(Site, blank=True, verbose_name="契約サイト")
  user = models.ManyToManyField(get_user_model(), blank=True, verbose_name="ユーザー")
  is_prioritize = models.BooleanField(default=False, verbose_name="プライオリタイズ")
  is_active = models.BooleanField(default=True, verbose_name="有効")

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('customer_list')


  class Meta:
    db_table = 'customer'

class CustomerContract(models.Model):
  goal_contacts_monthly = models.IntegerField(verbose_name="送信数ゴール（⽉）")
  goal_total_blogs = models.IntegerField(verbose_name="記事本数（⽉）")
  contract_period = models.IntegerField(verbose_name="契約期間 (ヶ月)")
  start_date = models.DateField(verbose_name="契約開始日")
  end_date = models.DateField(verbose_name="契約終了日")
  contract_period_option = models.IntegerField(verbose_name="オプション期間 (ヶ月)",null=True)
  start_date_option = models.DateField(verbose_name="オプション開始日",null=True)
  end_date_option = models.DateField(verbose_name="オプション終了日",null=True)
  created_date = models.DateTimeField(auto_now_add=True, verbose_name="作成日")
  last_updated = models.DateTimeField(auto_now=True, verbose_name="更新日")
  plan = models.ForeignKey(Group, on_delete=models.CASCADE, related_name="plan", verbose_name="プラン")
  customer = models.ForeignKey(Customer, on_delete=models.CASCADE, verbose_name="顧客名")
  option = models.ManyToManyField(Group, db_table="customer_contract_option", related_name="option", blank=True, verbose_name="オプション")
  is_active = models.BooleanField(default=False, verbose_name="有効")
  is_priority = models.BooleanField(default=False, verbose_name="Priority")
  comment = models.TextField(verbose_name="Comment",blank=True)
  payment_method = models.CharField(
    choices=(
      ("once","Once"),
      ("monthly","Monthly"),
      ("completely free","Completely free"),
      ("other","Other"),
    ),
    default="monthly",
    max_length=20
  )
  goal_main_channel = models.IntegerField(default=0)
  goal_op1 = models.IntegerField(default=0)
  goal_op2 = models.IntegerField(default=0)
  site_id_main_channel = models.IntegerField(default=-1)
  site_id_op_1 = models.IntegerField(default=-1)
  site_id_op_2 = models.IntegerField(default=-1)
  is_free = models.BooleanField(default=False, verbose_name="無償")
  contract_period_free = models.IntegerField(verbose_name="無償期間",null=True)
  start_date_free = models.DateField(verbose_name="無償開始日",null=True)
  end_date_free = models.DateField(verbose_name="無償終了日",null=True)

  def __str__(self):
    return f'{self.customer.name} : {self.start_date}' 

  def get_absolute_url(self):
    return reverse('customer_contract_list')

  class Meta:
    db_table = 'customer_contract'

class CustomerSetting(models.Model):

  hb_form_id = models.TextField(verbose_name="HubspotフォームID")
  default_file_password = models.CharField(max_length=20, verbose_name="ファイルパスワード (デフォルト)")
  created_date = models.DateTimeField(auto_now_add=True, verbose_name="作成日")
  last_updated = models.DateTimeField(auto_now=True, verbose_name="更新日")
  customer = models.ForeignKey(Customer, on_delete= models.CASCADE, verbose_name="顧客名")
  site = models.ForeignKey(Site,on_delete = models.CASCADE, verbose_name="契約サイト")
  is_main_channel = models.BooleanField(null=True, default=False, verbose_name="主チャンネル")

  class Meta:
    db_table = 'customer_setting'

class CustomerSettingAudit(models.Model):
  field = models.CharField(max_length=20)
  record = models.ForeignKey(CustomerSetting, on_delete=models.CASCADE)
  old_value = models.CharField(max_length=100)
  new_value = models.CharField(max_length=100)
  user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
  create_date = models.DateTimeField(auto_now_add=True)

  class Meta:
    db_table = 'customer_setting_audit'

class CustomerGroupPlanOption(models.Model):
  customer_group = models.ForeignKey(CustomerGroup, on_delete=models.CASCADE)
  auth_group = models.ForeignKey(Group, on_delete=models.CASCADE)
  type = models.CharField(
    choices=(
      ("plan","Plan"),
      ("option","Option"),
    ),
    default="plan",
    max_length=20
  )
  sort = models.IntegerField()
  
  def __str__(self):
    return self.auth_group.name
  
  class Meta:
    db_table = 'customer_group_plan_option'

class CustomerSeminarSetting(models.Model):
  name = models.CharField(max_length=255,null=True)
  list_hb_id = models.IntegerField(null=True)
  lp_id = models.CharField(max_length=45,null=True)
  dict_properties = models.TextField(null=True)
  last_updated = models.DateTimeField(auto_now=True)
  created_date = models.DateTimeField(auto_now_add=True)
  site = models.ForeignKey(Site,on_delete = models.CASCADE)
  customer = models.ForeignKey(Customer,on_delete = models.CASCADE)
  file_password = models.CharField(max_length=20,null=True)
  
  class Meta:
    db_table = 'customer_seminar_setting'

accu_project/SourceCode/f_1_1_customers/forms.py
from django import forms
from f_1_1_customers.models import *

class CustomerCreateForm(forms.ModelForm):
  class Meta:
    model = Customer
    fields = ['id', 'code', 'name','domain', 'site', 'customer_group','exclude_email','email_domain','is_prioritize','is_active']

  def clean_name(self):
    name = self.cleaned_data.get('name')
    customers = Customer.objects.filter(name=name)
    if len(customers) == 0:
      return name
    else:
      raise forms.ValidationError("Customer name is exist.")

  # def clean_domain(self):
  #   domain = self.cleaned_data.get('domain')
  #   customers = Customer.objects.filter(domain=domain)
  #   if len(customers) == 0:
  #     return domain
  #   else:
  #     raise forms.ValidationError("Customer domain is exist.")

accu_project/SourceCode/templates/apps/f_1_1_customers/customer_contract/customer_contract_create.html
{% include 'base/message.html' %}
<div>
  <form action="{{url('customer_contract_create',args=(customer_group_id,customer_id))}}" method="post"
    id="contract-create-form">
    {{ crispy(form) }}
    <input class="btn btn-primary mt-3" type="submit" value="Save">
  </form>
</div>

<script>

  $(document).ready(function () {
      //$('input##id_end_date').attr('disabled', true);
      $("#div_id_is_free").addClass("d-none");
      $("#div_id_goal_main_channel").addClass("d-none");
      $("#div_id_goal_op1").addClass("d-none");
      $("#div_id_goal_op2").addClass("d-none");
      $("#div_id_contract_period_option").addClass("d-none");
      $("#div_id_start_date_option").addClass("d-none");
      $("#div_id_end_date_option").addClass("d-none");
      $("#div_id_contract_period_free").addClass("d-none");
      $("#div_id_start_date_free").addClass("d-none");
      $("#div_id_end_date_free").addClass("d-none");
      $("#div_id_site_id_main_channel").addClass("d-none");
      $("#div_id_site_id_op_1").addClass("d-none");
      $("#div_id_site_id_op_2").addClass("d-none");
      
      
  });

  $("select#id_plan").change(function() {

    var plan_val = $(this).val();

    //Hard code giá trị ban đầu của goal
    if (plan_val == 1){
      $("#id_goal_contacts_monthly").val(10); //submission
      $("#id_goal_total_blogs").val(0); //blogs
    }

    if (plan_val == 2){
      $("#id_goal_contacts_monthly").val(10); //submission
      $("#id_goal_total_blogs").val(1); //blogs

    }

    if (plan_val == 3){
      $("#id_goal_contacts_monthly").val(20); //submission
      $("#id_goal_total_blogs").val(2); //blogs

    }

    if (plan_val == 1 || plan_val == 2 || plan_val == 3 ){
      $("#div_id_is_free").removeClass("d-none");
    }
    else{
      $("#div_id_is_free").addClass("d-none");
      $("#id_goal_contacts_monthly").val(10); //submission
      $("#id_goal_total_blogs").val(1); //blogs
    }
  });

  $("#id_is_free").change(function() {
  // Check input( $( this ).val() ) for validity here
    if ($("#id_is_free").is(":checked")) {
      $("#div_id_contract_period_free").removeClass("d-none");
      $("#div_id_start_date_free").removeClass("d-none");
      $("#div_id_end_date_free").removeClass("d-none");

    }

    if( !$("#id_is_free").is(":checked")){
      $("#div_id_contract_period_free").addClass("d-none");
      $("#div_id_start_date_free").addClass("d-none");
      $("#div_id_end_date_free").addClass("d-none");
    }
    
  });

  $("#id_option_2").change(function() {
  // Check input( $( this ).val() ) for validity here
    if ($("#id_option_2").is(":checked")) {
      $("#div_id_contract_period_option").removeClass("d-none");
      $("#div_id_start_date_option").removeClass("d-none");
      $("#div_id_end_date_option").removeClass("d-none");
      
      $("#div_id_site_id_main_channel").removeClass("d-none");
      $("#div_id_site_id_op_1").removeClass("d-none");
      $("#div_id_site_id_op_2").removeClass("d-none");
      $("#div_id_goal_main_channel").removeClass("d-none");
      $("#div_id_goal_op1").removeClass("d-none");
      $("#div_id_goal_op2").removeClass("d-none");
    }
    else{
      $("#div_id_site_id_main_channel").addClass("d-none");
      $("#div_id_site_id_op_1").addClass("d-none");
      $("#div_id_site_id_op_2").addClass("d-none");
      $("#div_id_goal_main_channel").addClass("d-none");
      $("#div_id_goal_op1").addClass("d-none");
      $("#div_id_goal_op2").addClass("d-none");
    }

    if( !$("#id_option_2").is(":checked") && !$("#id_option_1").is(":checked")){
      $("#div_id_contract_period_option").addClass("d-none");
      $("#div_id_start_date_option").addClass("d-none");
      $("#div_id_end_date_option").addClass("d-none");
    }

  });

  $("#id_option_1").change(function() {
  // Check input( $( this ).val() ) for validity here
    if ($("#id_option_1").is(":checked")) {
      $("#div_id_contract_period_option").removeClass("d-none");
      $("#div_id_start_date_option").removeClass("d-none");
      $("#div_id_end_date_option").removeClass("d-none");

    }

    if( !$("#id_option_2").is(":checked") && !$("#id_option_1").is(":checked")){
      $("#div_id_contract_period_option").addClass("d-none");
      $("#div_id_start_date_option").addClass("d-none");
      $("#div_id_end_date_option").addClass("d-none");
    }
    
  });

  
  

  show_date_format("id_start_date", value="yyyy-mm-dd")
  show_date_format("id_end_date", value="yyyy-mm-dd", disable=true)

  var contract_period_change = false;
  var contract_start_date_change = false;
  $("input#id_contract_period").change(function () {

    contract_period_change = true;
    var contract_period = $("input#id_contract_period").val();
    var start_date = $("#id_start_date").val();
    if (start_date != "") {
      var no_of_months = $("input#id_contract_period").val();
      var currentDate = moment(start_date);
      var future_date = moment(currentDate).add(no_of_months, 'months').format('YYYY-MM-DD');
      var future_date = moment(future_date).add(-1, 'days').format('YYYY-MM-DD');
      $("#id_end_date").val(future_date);
    }
  });

  $("#id_start_date").change(function () {
    contract_start_date_change = true
    var contract_period = $("input#id_contract_period").val();
    var start_date = $("#id_start_date").val();
    if (contract_period != "") {
      var no_of_months = $("input#id_contract_period").val();
      var currentDate = moment(start_date);
      var future_date = moment(currentDate).add(no_of_months, 'months').format('YYYY-MM-DD');
      var future_date = moment(future_date).add(-1, 'days').format('YYYY-MM-DD');
      $("#id_end_date").val(future_date);
    }
  });

  show_date_format("id_start_date_option", value="yyyy-mm-dd")
  show_date_format("id_end_date_option", value="yyyy-mm-dd", disable=true)

  var contract_period_option_change = false;
  var contract_start_date_option_change = false;
  $("input#id_contract_period_option").change(function () {

    contract_period_option_change = true;
    var contract_period = $("input#id_contract_period_option").val();
    var start_date_option = $("#id_start_date_option").val();
    if (start_date_option != "") {
      var no_of_months = $("input#id_contract_period_option").val();
      var currentDate = moment(start_date_option);
      var future_date = moment(currentDate).add(no_of_months, 'months').format('YYYY-MM-DD');
      var future_date = moment(future_date).add(-1, 'days').format('YYYY-MM-DD');
      $("#id_end_date_option").val(future_date);
    }
  });

  $("#id_start_date_option").change(function () {
    contract_start_date_option_change = true
    var contract_period = $("input#id_contract_period_option").val();
    var start_date_option = $("#id_start_date_option").val();
    if (contract_period != "") {
      var no_of_months = $("input#id_contract_period_option").val();
      var currentDate = moment(start_date_option);
      var future_date = moment(currentDate).add(no_of_months, 'months').format('YYYY-MM-DD');
      var future_date = moment(future_date).add(-1, 'days').format('YYYY-MM-DD');
      $("#id_end_date_option").val(future_date);
    }
  });

  show_date_format("id_start_date_free", value="yyyy-mm-dd")
  show_date_format("id_end_date_free", value="yyyy-mm-dd", disable=true)

  var contract_period_free_change = false;
  var contract_start_date_free_change = false;
  $("input#id_contract_period_free").change(function () {

    contract_period_free_change = true;
    var contract_period = $("input#id_contract_period_free").val();
    var start_date_free = $("#id_start_date_free").val();
    if (start_date_free != "") {
      var no_of_months = $("input#id_contract_period_free").val();
      var currentDate = moment(start_date_free);
      var future_date = moment(currentDate).add(no_of_months, 'months').format('YYYY-MM-DD');
      var future_date = moment(future_date).add(-1, 'days').format('YYYY-MM-DD');
      $("#id_end_date_free").val(future_date);
    }
  });

  $("#id_start_date_free").change(function () {
    contract_start_date_free_change = true
    var contract_period = $("input#id_contract_period_free").val();
    var start_date_free = $("#id_start_date_free").val();
    if (contract_period != "") {
      var no_of_months = $("input#id_contract_period_free").val();
      var currentDate = moment(start_date_free);
      var future_date = moment(currentDate).add(no_of_months, 'months').format('YYYY-MM-DD');
      var future_date = moment(future_date).add(-1, 'days').format('YYYY-MM-DD');
      $("#id_end_date_free").val(future_date);
    }
  });



  $("#contract-create-form").submit(function (e) {
    e.preventDefault(); // avoid to execute the actual submit of the form.
    var form = $(this);
    disable_element(form)
    var url = form.attr('action');
    var start_date = $("#id_start_date").val();
    var end_date = $("#id_end_date").val();
    var start_date_option = $("#id_start_date_option").val();
    var end_date_option = $("#id_end_date_option").val();
    var start_date_free = $("#id_start_date_free").val();
    var end_date_free = $("#id_end_date_free").val();
    
    data = form.serialize() + `&end_date=${end_date}` + `&start_date=${start_date}`
    if (start_date_free != "yyyy-mm-dd" & end_date_free !="yyyy-mm-dd"){
      data += `&end_date_free=${end_date_free}` + `&start_date_free=${start_date_free}`
    }

    if (start_date_option != "yyyy-mm-dd" & end_date_option !="yyyy-mm-dd"){
      data += `&end_date_option=${end_date_option}` + `&start_date_option=${start_date_option}`
    }
   
    $.ajax({
      type: "POST",
      url: url,
      data: data, // serializes the form's elements.
      success: function (data) {
        form.parent().html(data);
        enable_element(form)
      }
    })
  });
</script>

accu_project/SourceCode/templates/apps/f_1_1_customers/customer_contract/customer_contract_delete.html
<form action="{{url('customer_contract_delete',args=(customercontract.pk,))}}" id="customer-delete-form" method="post">
  <div class="text-center">
    <p style="font-size: 20px;"><span class="text-danger">【{{customercontract.start_date}}】</span>を削除してもよろしいですか。</p>
    <input type="hidden" name="csrfmiddlewaretoken" value="{{csrf_token}}">
    <input class="btn btn-danger" type="submit" value="Confirm">
  </div>
</form>

<script type="text/javascript">
  $("input[type='submit']").click(function(){
    disable_element($('#modalDeleteContract #modalBody'))
  });
</script>