accu_project/SourceCode/f_7_1_accounts/urls.py
# accounts/urls.py
from django.conf.urls import url, include
from f_7_1_accounts import views
from django.urls import path
from django.contrib.auth import views as auth_views

urlpatterns = [
   url(r'^verifyError$', views.verifyError, name='verifyError'),
   url(r'^resetError$', views.resetError, name='resetError'),
   url(r'^login/$', views.LoginView.as_view(), name='login'),
   url(r'^authentication/$', views.AuthenticationPageView.as_view(), name='authentication'),
   path('signup/<int:group_id>/<int:customer_id>/', views.SignUpView.as_view(), name='signup'),
   url(r'^user-list/$', views.UserListView.as_view(), name='user_list'),
   # path('verify/<str:uidb64>/<str:token>/', views.verify, name='verify'),
   path('verify/<str:uidb64>/<str:token>/', views.VerifyV2.as_view(), name='verify'),
   path('verify-done/<int:user_id>/', views.verifyDone, name='set_password_done'),
   path('<int:pk>/update-password', views.UserChangePassWord.as_view(), name='update_password'),
   path('<int:pk>/update', views.UserUpdateView.as_view(), name='user_update'),
   path('<int:pk>/delete', views.UserDeleteView.as_view(), name='user_delete'),
   path('customer-user', views.CustomerUserView.as_view(), name='customer_user'),
   path('admin-user', views.AdminUserView.as_view(), name='admin_user'),
   path('delete-bulk', views.UserDeleteBulkView.as_view(), name='user_delete_bulk'),
   path('login-user/<int:user_id>/', views.loginUser, name='login_user'),
   path('resend-code/', views.reSendCode, name='resend_code'),

   # url(r'^password/$', views.change_password, name='change_password'),
   path('change_password/', views.PasswordChangeView.as_view() ,name = 'change_password'),
   # path('password_reset/', auth_views.PasswordResetView.as_view(html_email_template_name='registration/password_reset_html_email.html'), name = 'password_reset'),
   path('user-list/download-user/', views.download_data_user, name='download_data_user'),

   path('password_reset/', views.UserPasswordForgot.as_view(), name='password_reset'),
   path('password_reset/done', views.passwordResetDone),
   path('set-password/<str:uidb64>/<str:token>/', views.UserSetPassword.as_view(), name='set_password'),
   path('set-password/done', views.setPassworDone, name='reset_password_done'),
   path('remind-bulk', views.UserRemindBulkView.as_view(), name='user_remind_bulk'),

]

accu_project/SourceCode/main/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from main import views

urlpatterns = [
    path('admin/login/', views.redirect_login),
    path('admin/', admin.site.urls),
    path('customers/', include('f_1_1_customers.urls')), 
    path('sites/', include('f_1_2_sites.urls')), 
    path('accounts/', include('f_7_1_accounts.urls')), 
    path('accounts/', include('django.contrib.auth.urls')), 
    path('', include('accu_dashboard.urls')),


]

accu_project/SourceCode/f_1_1_customers/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import Group
from django.contrib.auth import get_user_model
from datetime import datetime
from dateutil.relativedelta import relativedelta

from f_1_2_sites.models import Site
# Create your models here.
class CustomerGroup(models.Model):
  name = models.CharField(max_length=50)
  site = models.ManyToManyField(Site, blank=True, verbose_name="契約サイト")

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('customer_group_list')
  
  class Meta:
    db_table = 'customer_group'

class Customer(models.Model):
  id = models.CharField(
    max_length=6,
    unique=True,
    primary_key=True
  )
  code = models.CharField(max_length=30, verbose_name="顧客コード")
  exclude_email = models.TextField(verbose_name="除外メールアドレス", help_text="例：@tpcompany.net")
  email_domain = models.TextField(verbose_name="除外ドメイン", help_text="例：tpcompany.net")
  name = models.CharField(max_length=30, verbose_name="顧客名")
  created_date = models.DateTimeField(auto_now_add=True, verbose_name="作成日")
  last_updated = models.DateTimeField(auto_now=True, verbose_name="更新日")
  domain = models.CharField(max_length=100,blank=True, verbose_name="サイトURL", help_text="例：https://www.tpcompany.net")
  customer_group = models.ForeignKey(CustomerGroup, on_delete=models.CASCADE, verbose_name="グループ")
  site = models.ManyToManyField(Site, blank=True, verbose_name="契約サイト")
  user = models.ManyToManyField(get_user_model(), blank=True, verbose_name="ユーザー")
  is_prioritize = models.BooleanField(default=False, verbose_name="プライオリタイズ")
  is_active = models.BooleanField(default=True, verbose_name="有効")

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('customer_list')


  class Meta:
    db_table = 'customer'

class CustomerContract(models.Model):
  goal_contacts_monthly = models.IntegerField(verbose_name="送信数ゴール（⽉）")
  goal_total_blogs = models.IntegerField(verbose_name="記事本数（⽉）")
  contract_period = models.IntegerField(verbose_name="契約期間 (ヶ月)")
  start_date = models.DateField(verbose_name="契約開始日")
  end_date = models.DateField(verbose_name="契約終了日")
  contract_period_option = models.IntegerField(verbose_name="オプション期間 (ヶ月)",null=True)
  start_date_option = models.DateField(verbose_name="オプション開始日",null=True)
  end_date_option = models.DateField(verbose_name="オプション終了日",null=True)
  created_date = models.DateTimeField(auto_now_add=True, verbose_name="作成日")
  last_updated = models.DateTimeField(auto_now=True, verbose_name="更新日")
  plan = models.ForeignKey(Group, on_delete=models.CASCADE, related_name="plan", verbose_name="プラン")
  customer = models.ForeignKey(Customer, on_delete=models.CASCADE, verbose_name="顧客名")
  option = models.ManyToManyField(Group, db_table="customer_contract_option", related_name="option", blank=True, verbose_name="オプション")
  is_active = models.BooleanField(default=False, verbose_name="有効")
  is_priority = models.BooleanField(default=False, verbose_name="Priority")
  comment = models.TextField(verbose_name="Comment",blank=True)
  payment_method = models.CharField(
    choices=(
      ("once","Once"),
      ("monthly","Monthly"),
      ("completely free","Completely free"),
      ("other","Other"),
    ),
    default="monthly",
    max_length=20
  )
  goal_main_channel = models.IntegerField(default=0)
  goal_op1 = models.IntegerField(default=0)
  goal_op2 = models.IntegerField(default=0)
  site_id_main_channel = models.IntegerField(default=-1)
  site_id_op_1 = models.IntegerField(default=-1)
  site_id_op_2 = models.IntegerField(default=-1)
  is_free = models.BooleanField(default=False, verbose_name="無償")
  contract_period_free = models.IntegerField(verbose_name="無償期間",null=True)
  start_date_free = models.DateField(verbose_name="無償開始日",null=True)
  end_date_free = models.DateField(verbose_name="無償終了日",null=True)

  def __str__(self):
    return f'{self.customer.name} : {self.start_date}' 

  def get_absolute_url(self):
    return reverse('customer_contract_list')

  class Meta:
    db_table = 'customer_contract'

class CustomerSetting(models.Model):

  hb_form_id = models.TextField(verbose_name="HubspotフォームID")
  default_file_password = models.CharField(max_length=20, verbose_name="ファイルパスワード (デフォルト)")
  created_date = models.DateTimeField(auto_now_add=True, verbose_name="作成日")
  last_updated = models.DateTimeField(auto_now=True, verbose_name="更新日")
  customer = models.ForeignKey(Customer, on_delete= models.CASCADE, verbose_name="顧客名")
  site = models.ForeignKey(Site,on_delete = models.CASCADE, verbose_name="契約サイト")
  is_main_channel = models.BooleanField(null=True, default=False, verbose_name="主チャンネル")

  class Meta:
    db_table = 'customer_setting'

class CustomerSettingAudit(models.Model):
  field = models.CharField(max_length=20)
  record = models.ForeignKey(CustomerSetting, on_delete=models.CASCADE)
  old_value = models.CharField(max_length=100)
  new_value = models.CharField(max_length=100)
  user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
  create_date = models.DateTimeField(auto_now_add=True)

  class Meta:
    db_table = 'customer_setting_audit'

class CustomerGroupPlanOption(models.Model):
  customer_group = models.ForeignKey(CustomerGroup, on_delete=models.CASCADE)
  auth_group = models.ForeignKey(Group, on_delete=models.CASCADE)
  type = models.CharField(
    choices=(
      ("plan","Plan"),
      ("option","Option"),
    ),
    default="plan",
    max_length=20
  )
  sort = models.IntegerField()
  
  def __str__(self):
    return self.auth_group.name
  
  class Meta:
    db_table = 'customer_group_plan_option'

class CustomerSeminarSetting(models.Model):
  name = models.CharField(max_length=255,null=True)
  list_hb_id = models.IntegerField(null=True)
  lp_id = models.CharField(max_length=45,null=True)
  dict_properties = models.TextField(null=True)
  last_updated = models.DateTimeField(auto_now=True)
  created_date = models.DateTimeField(auto_now_add=True)
  site = models.ForeignKey(Site,on_delete = models.CASCADE)
  customer = models.ForeignKey(Customer,on_delete = models.CASCADE)
  file_password = models.CharField(max_length=20,null=True)
  
  class Meta:
    db_table = 'customer_seminar_setting'

accu_project/SourceCode/f_7_1_accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
# Create your models here

class AccountUserSession(models.Model):
  secret_key = models.CharField(max_length=255)
  last_token = models.CharField(max_length=10,default='')
  sent_times = models.IntegerField(default=0)
  last_updated = models.DateTimeField(auto_now=True)
  created_date = models.DateTimeField(auto_now_add=True)
  is_verified = models.BooleanField(default=0)
  last_verify_token = models.CharField(max_length=255,default='')
  user = models.ForeignKey(get_user_model(),on_delete=models.CASCADE)

  class Meta:
    db_table = 'account_user_session'

accu_project/SourceCode/f_7_1_accounts/forms.py
from django import forms
from f_7_1_accounts.authentication import utils as auth_utils
from f_7_1_accounts.password import utils as password_utils
from django.contrib.auth import get_user_model
from django.contrib.auth.forms  import UserCreationForm, UserChangeForm
from f_1_1_customers.models import Customer, CustomerGroup
from django.contrib.auth.models import User
from django.contrib import messages
from .tokens import account_reset_password_token

class LoginCodeForm(forms.Form):
  code = forms.CharField(max_length=6, label="セキュリティコード")
  def __init__(self, *args, **kwargs):
    self.user = kwargs.pop('user',None)
    super().__init__(*args, **kwargs)

  def clean_code(self):
    is_valid = auth_utils.check_token(self.user.id, self.cleaned_data['code'])
    if not is_valid:
      raise forms.ValidationError("セキュリティコードが正しくありません。ご確認の上、再度入力してください。")

class CustomUserCreationForm(UserCreationForm):
  class  Meta:
    model = get_user_model()
    fields = ('email', 'username',)

class CustomUserChangeForm(UserChangeForm):
  class Meta:
    model = get_user_model()
    fields = ('email','username',)

class SignUpForm(forms.Form):
  class Meta:
    model = get_user_model()
    fields = ('group', 'customer', 'email', 'last_name', 'first_name', 'domain',)
  email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.', required=False, label="メールアドバイス")
  group = forms.ChoiceField(required=False, label="グループ")
  customer = forms.ChoiceField(required=False, label="顧客名")
  last_name = forms.CharField(max_length=60, label="姓")
  first_name = forms.CharField(required=False,max_length=50, label="名", initial='')
  domain = forms.CharField(max_length=2550, label="ドメイン")

  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
  
  # def clean_email(self):
  #   email = self.cleaned_data.get('email')
  #   if len(User.objects.filter(email=email)) > 0:
  #     raise forms.ValidationError("Email is exist")
  #   return email
  
class CustomPasswordChangeForm(forms.Form):
  new_password1 = forms.CharField(label='パスワード', widget=forms.PasswordInput, required=True)
  new_password2 = forms.CharField(label='パスワード再入力', widget=forms.PasswordInput, required=True)

  field_order = ['new_password1', 'new_password2']

  def __init__(self, user, *args, **kwargs):
    self.user = user
    super().__init__(*args, **kwargs)

  def clean_new_password2(self):
    if self.is_valid():
      password1 = self.cleaned_data.get('new_password1')
      password2 = self.cleaned_data.get('new_password2')
      if password1 != password2:
        raise forms.ValidationError("The two password fields didn't match")

      return password2

  def save(self, commit=True):
    password = self.cleaned_data["new_password1"]
    self.user.set_password(password)
    if commit:
      self.user.save()
    return self.user

class ChangePasswordForm(forms.Form):

  current_password = forms.CharField(label='Current Password', widget=forms.PasswordInput, required=True)
  new_password1 = forms.CharField(label='New Password', widget=forms.PasswordInput, required=True)
  new_password2 = forms.CharField(label='Confirm New Password', widget=forms.PasswordInput, required=True)

  field_order = ['current_password', 'new_password1', 'new_password2']

  def __init__(self, *args, **kwargs):
    self.user = kwargs.pop('user',None)
    super().__init__( *args, **kwargs)

  def clean_current_password(self):
    if self.is_valid():
      current_password = self.cleaned_data.get('current_password')
      valid_current_password = self.user.check_password(current_password)
      if not valid_current_password:
        raise forms.ValidationError("Current password is incorrect!")

      return current_password

  def clean_new_password2(self):
    if self.is_valid():
      password1 = self.cleaned_data.get('new_password1')
      password2 = self.cleaned_data.get('new_password2')
      if password1 != password2:
        raise forms.ValidationError("The two password fields didn't match!")
      return password2
  
  

  def save(self, commit=True):
    password = self.cleaned_data["new_password1"]
    self.user.set_password(password)
    if commit:
      self.user.save()
    return self.user

class PasswordForgotForm(forms.Form):
  inputfield = forms.CharField(max_length=50, label="メールアドレス")
  def clean_inputfield(self):
    inputfield = self.cleaned_data['inputfield']
    '''
    if '@' in inputfield:
      users = User.objects.filter(email=inputfield)
      assert len(users) > 0
      user = users[0]
      if len(users) == 1:
        if user.is_active == 0:
          if user.last_login is None:
            raise forms.ValidationError("User is activating. Please confirm first")
          else:
            raise forms.ValidationError("User is locked. Can't reset password")
      token = account_reset_password_token.make_token(user)
      # Send email with email
      password_utils.sent_token(inputfield, token, email=inputfield)
    else:
    '''
    if User.objects.filter(username=inputfield).exists():
      user = User.objects.get(username=inputfield)
      if user.is_active == 0:
        if user.last_login is None:
          raise forms.ValidationError("ユーザーがまだアクティベーションされていません。")
        else:
          raise forms.ValidationError("ユーザーがロックされています。")
      else:
        # Send email with username
        token = account_reset_password_token.make_token(user)
        password_utils.sent_token(user.email, token, username=inputfield)
    else:
      raise forms.ValidationError("メールアドレスが見つかりませんでした。")

accu_project/SourceCode/templates/apps/f_7_1_accounts/authentication.html
{% extends 'base/base.html' %}


{% block main %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-7">
      <div class="card-group" style="padding-top: 150px">
        <div class="card card-login p-4">
          <div class="card-body">
            <form method="post">
              <h1>セキュリティコードを入力</h1>
              <small class="text-muted mb-3 d-inline-block">ログイン時のメールアドレスに確認メールが届きます。<br>
                表示される6桁のコードを入力してください。（有効時間：5分）</small>
              {{crispy(form)}}
              <input type="hidden" value="{{csrf_token}}">
              <button class="btn btn-primary">認証</button>
              <div class="row mt-3">
                <div class="col-12">
                  
                  <p>
                    <span class="resend text-muted text-resend">セキュリティコードが届かない場合は、再送をお試しください。</span>
                    <a class="resend resend-button" id='reSend'>セキュリティコードを再送</a>
                  </p>
                  <hr/>
                  <p>
                    <small>お問い合わせは<a href="https://www.accu.net/microsoft/contact" target="_blank"><u>こちら</u></a>からお願いします。</small>
                  </p>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock main %}

{% block script %}
<script type="text/javascript">
  var reSend = document.getElementById('reSend');
  reSend.addEventListener('click', function(event){
    $(".message-resend").remove();
    event.preventDefault();
    reSend.disabled = true;
    disable_element($(".card-login"))
    $.ajax({
      type: "POST",
      url: `/accounts/resend-code/`,
      dataType: "html",
      data : { 
          'csrfmiddlewaretoken' : '{{ csrf_token }}' 
      },
      success: function(data)
      {
        // if(typeof data == 'string') {
        //   reSend.className = 'btn btn-secondary';
        // }else{
        //   reSend.disabled = false;
        //   reSend.className = 'btn btn-primary';
        // }
        $("<span class='d-block resend message-resend w-100 text-success'><i class='fa fa-check mr-1'></i>あなたのメールアドレスへセキュリティコードを送信しました。</span>").insertBefore(".text-resend");
        enable_element($(".card-login"));
      }
    });

  });
</script>
{% endblock %}

accu_project/SourceCode/templates/apps/f_7_1_accounts/signup.html
{% include 'base/message.html' %}
<div>
  <form action="" method="post" id="user-create-form">
    {{ crispy(form) }}
    <input class="btn btn-primary mt-3" type="submit" value="Sign up" id='id_submit' disabled=true>
  </form>
</div>

<script>
  $("#user-create-form").submit(function(e) {
    e.preventDefault(); // avoid to execute the actual submit of the form.
    var form = $(this);
    disable_element(form)
    
    var group_id = 1;
    var customer_id = $("#id_customer").val();
    var url = '/accounts/signup/' + group_id + '/' + customer_id + '/'
    
    $.ajax({
      type: "POST",
      url: url,
      data: form.serialize(), // serializes the form's elements.
      success: function(data)
      {
        form.parent().html(data);
        enable_element(form)
        }
      })
    });

    $('input#id_email').blur(function() {   
        var email_value = $('#id_email').val();
        var domains = $('#id_domain').val();
        domains = domains.slice(1,domains.length-1);
        domains = domains.replaceAll("'","").replaceAll(" ","");
        list_domain = domains.split(',');
        list_domain = list_domain.map(x => x.replace('@', ''));
        domain = email_value.slice(email_value.indexOf('@')+1,email_value.length);
        if (list_domain[0] !== ''){
          var check_email = list_domain.includes(domain);
          if (check_email){
            $("#hint_id_email").text(``);
            $('#id_submit').attr('disabled', false);
          }
          else{
            $("#hint_id_email").text(`Email must contains ${list_domain}`);
            $('#id_submit').attr('disabled', true);
          }
        }else{
          $("#hint_id_email").text(`You must input list email domain before`);
          $('#id_submit').attr('disabled', true);
        }
    });

</script>

accu_project/SourceCode/templates/apps/f_7_1_accounts/user_list.html
{% extends 'base/base.html' %}

{% block breadcrumb %}
<li class="breadcrumb-item active"><span>Users Management</span></li>
{% endblock %}

{% block main %}
<div class="modal fade" id="form-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
     <div class="modal-dialog">
       <div class="modal-content">
         <div class="modal-header">
           <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
           <h4 class="modal-title">Modal title</h4>
         </div>
         <div id="form-modal-body" class="modal-body">
           ...
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
 </div>

<div class="container">
  <h1 class="pt-4 text-center font-weight-bold text-primary">
    Users Management
  </h1>
</div>

<div class="row mx-3 position-relative table-loading">
  <div class="col-12 custom-datatable-toolbar">

    <div class="row">
      <div class="col-8">

        <select class="form-control form-control-toolbar form-control-sm ml-2" id="id_site" onchange="add_param()">
          <option value="-1">-- Site --</option>
          {% for site in list_sites%}
          <option value="{{site.pk}}" {{ "selected" if request.GET.get('site') == site.pk|string }}>{{site.name}}
          </option>
          {% endfor %}
        </select>

        <select class="form-control form-control-toolbar form-control-sm ml-2" id="id_customer" onchange="add_param()">
          <option value="-1">-- All Customer --</option>
          {% for customer in list_customers %}
              <option value="{{customer.id}}" {{ "selected" if request.GET.get('customer') == customer.id|string }}>{{customer.name}} ({{customer.code}})</option>
          {% endfor %}
        </select>

        <select class="form-control form-control-toolbar form-control-sm ml-2" id="status" onchange="add_param()">
            <option value="2" {{ "selected" if request.GET.get('status') == '2' }}>-- All Status --</option>
            <option value="1" {{ "selected" if request.GET.get('status') == '1' }}>Active</option>
            <option value="0" {{ "selected" if request.GET.get('status') == '0' }}>Waiting</option>
            <option value="-1" {{ "selected" if request.GET.get('status') == '-1' }}>Locked</option>
        </select>


      </div>

      <div class="col-4 text-right">
        {% if request.GET.get('group') != none and request.GET.get('group') != '-1' and request.GET.get('customer') != none and request.GET.get('customer') != '-1' %}
        <button data-toggle="modal" data-target="#modalCreatUser" class="btn btn-light border btn-sm mr-2" type="button" margin="100px"
            data-toggle="modal" 
            data-target="#modalCreatUser" 
          ><i class="fa fa-plus mr-1"></i>Create User</button>
        {% endif %}
        <div class="dropdown d-inline">
          <button class="btn-light border dropdown-toggle btn-sm" type="button"
            id="dropdownAction" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Action
          </button>
          <div class="dropdown-menu pointer" aria-labelledby="dropdownAction">
            <a class="dropdown-item" href="download-user?group={{request.GET.get('group',-1)}}&customer={{request.GET.get('customer',-1)}}&status={{request.GET.get('status',2)}}&search={{request.GET.get('search','')}}"><i class="fa fa-download mr-1"></i>Export CSV</a>
            <button data-toggle="modal" class="dropdown-item text-danger" data-target="#modalDeleteBulkUser">
              <i class="fa fa-trash mr-1 text-danger"></i>Delete multiple
            </button>

            <button data-toggle="modal" class="dropdown-item text-danger" data-target="#modalRemindBulkUser">
              <i class="fa fa-trash mr-1 text-danger"></i>Remind multiple user
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-12 mt-3">
    <table id="table_data" class="table table-not-in-card table-wrapper table-hover">
      <thead>
        <tr>
          <th style="width: 0px;" class="no-sort"><input onclick="check_uncheck_all(this);" type="checkbox" name="checkAll" id="check_all"></th>
          <th>Email</th>
          <th>User-Name</th>
          <th>Full Name</th>
          <th>Customer</th>
          <th>Status</th>
          <th class="text-nowrap">Action</th>
        </tr>
      </thead>
      <tbody>
        {% for user in list_users %}
        <tr>
          <td class="td-check"><input type="checkbox" name="check_all_item" class="checkbox" value="{{user.pk}}"></td>
          <td>{{user.email}}</td>
          <td>{{user.username}}</td>
          <td>{{user.first_name}} {{user.last_name}}</td>
          <td>{{user.customer_name}} 
            <small class="text-muted d-block" style="line-height: 5px;">({{user.customer_code}})</small>
          </td>
          <td>
            {% if user.last_login is none and user.is_active == False%}
            <span class="badge badge-warning"><i class="fa fa-close mr-1"></i>Ativating</span>
            {% elif user.is_active == True %}
            <span class="badge badge-success"><i class="fa fa-check mr-1"></i>Active</span>
            {% else %}
            <span class="badge badge-danger"><i class="fa fa-close mr-1"></i>Locked</span>
            {% endif %}
          </td>
          <td class="text-nowrap">
            <div class="dropdown">
              <button class="btn-light border dropdown-toggle btn-sm dropdown-in-table" type="button"
                id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                More
              </button>
              <div class="dropdown-menu " aria-labelledby="dropdownMenuButton">
                <button data-toggle="modal" class="dropdown-item" data-target="#modalUpdateUser"
                  data-user-id="{{user.pk}}">
                  <i class="fa fa-edit mr-1"></i>Update
                </button>
                {% if request.user.is_superuser == True %}
                <button data-toggle="modal" class="dropdown-item" data-target="#modalLoginUser"
                  data-user-email="{{user.email}}" data-user-id="{{user.pk}}">
                  <i class="fa fa-sign-in mr-1"></i>Login
                </button>
                {% endif %}
                <button data-toggle="modal" class="dropdown-item text-danger" data-target="#modalDeleteUser"
                  data-user-id="{{user.pk}}">
                  <i class="fa fa-trash mr-1 text-danger"></i>Delete
                </button>
              </div>
            </div>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% with 
  modal_id = 'modalUpdateUser',
  modal_title='Update User' ,
  modal_body_tmp = 'apps/f_7_1_accounts/modal_user_update.html'
%}
{% include 'popup/popup_update.html' %}
{% endwith %}

{% with 
  modal_id = 'modalDeleteUser',
  modal_title='Delete User' ,
  modal_body_tmp = 'apps/f_7_1_accounts/modal_user_delete.html'
%}
{% include 'popup/popup_delete.html' %}
{% endwith %}

{% with 
  modal_id = 'modalLoginUser',
  modal_title='Login User' ,
  modal_body_tmp = 'apps/f_7_1_accounts/modal_user_login.html'
%}
{% include 'popup/popup_login.html' %}
{% endwith %}

{% with 
  modal_id = 'modalCreatUser',
  modal_title='Create New User' ,
  modal_body_tmp = 'apps/f_7_1_accounts/modal_signup.html'
%}
  {% include 'popup/popup_create.html' %}
{% endwith %}

{% with 
  modal_id = 'modalDeleteBulkUser',
  modal_title='Delete Bulk User' ,
  modal_body_tmp = 'apps/f_7_1_accounts/modal_user_delete_bulk.html'
%}
{% include 'popup/popup_delete_bulk.html' %}
{% endwith %}

{% with 
  modal_id = 'modalRemindBulkUser',
  modal_title='Remind Bulk User' ,
  modal_body_tmp = 'apps/f_7_1_accounts/modal_user_remind_bulk.html'
%}
{% include 'popup/popup_remind_bulk.html' %}
{% endwith %}

{% endblock main %}



{% block script %}
<script type="text/javascript">
  $(document).ready(function () {

    // $.extend( $.fn.dataTable.defaults, {
    //     searching: false,
    //     ordering:  false
    // } );
    var table = $('#table_data').DataTable(get_option_datatable())

    show_sort_datatable(table)
  });
  function add_param(){
    disable_element($(".table-loading"))
    var group = 1;
    var customer = $("#id_customer").val();
    var status = $("#status").val();
    var search = $("#search").val();
    var site = $("#id_site").val();

    window.location.search = `?group=${group}&site=${site}&customer=${customer}&status=${status}&search=${search}`
  }
</script>

{% endblock %}